#networks:
#  app-network:
#    name: course-network
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.15.0.0/24

services:
  api:
    build: .
    container_name: api
    restart: always
    command: sh -c "sleep 5 && 
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/usr/src/
    ports:
      - "8000:8000"
#    networks:
#      - app-network
    depends_on:
      - db
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SETTINGS_MODULE=Youtube_insights.settings

  db:
    image: postgres:17.0-alpine
    container_name: db
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#    networks:
#      - app-network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
#    networks:
#      - app-network
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data
    depends_on:
      - db


volumes:
  postgres-data:
  pgadmin-data:
